BugOA/BugOA/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

apps/users/urls.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/8/6 上午1:06
# @Author  : Zheng Xingtao
# @File    : urls.py.py

from .views import *
from django.conf.urls import url

urlpatterns = [
    url(r'^logout/$', logout, name="logout"),
    url(r'^sms/$', send_sms, name="send_sms"),
    url(r'^image/code/$', image_code, name="image_code"),
    url(r'^register/$', Register.as_view(), name="register"),
    url(r'^login/sms/$', LoginSms.as_view(), name="login_sms"),
    url(r'^login/user/$', LoginUser.as_view(), name="login_user"),
]

cms/urls.py
from django.contrib import admin
from django.views.static import serve
from setting.develop import MEDIA_ROOT
from django.conf.urls import url, include

from django.views.generic.base import TemplateView, RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),  # index页面
    url(r'^favicon\.ico$', RedirectView.as_view(url=r'static/img/favicon.ico')),  # favicon图标
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    url(r'^user/', include(('users.urls', "user"), namespace="user")),  # 使用namespace， 防止多个app时前缀重名
    url(r'^project/', include(('project.urls', "project"), namespace="project")),
    url(r'^manage/(?P<project_id>\d+)/', include(('manages.urls', "manages"), namespace="manages")),
]

templates/code.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="../static/js/digitalrain.js"></script>
</head>

<body>

</body>
</html>

templates/index.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}
    首页
{% endblock %}

{% block css %}
    <style>
        img {
            width: 100%;
        }
    </style>
{% endblock %}

{% block content %}
    <div>
        <img src="{% static 'img/index/index-1.png' %}" alt="">
        <img src="{% static 'img/index/index-2.png' %}" alt="">
        <img src="{% static 'img/index/index-3.png' %}" alt="">
        <img src="{% static 'img/index/index-4.png' %}" alt="">
    </div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="../static/js/digitalrain.js"></script>
</head>

<body>
</body>
</html>

templates/login_sms.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}
    短信登录
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
{% endblock %}

{% block content %}
    <div class="account">
        <div class="title">短信登录</div>
        <form id="smsForm" method="POST" novalidate>
            {% csrf_token %}

            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row">
                            <div class="col-md-7">
                                {{ field }}
                                <span class="error-msg"></span>
                            </div>
                            <div class="col-md-5">
                                <input id="btnSms" type="button" class="btn btn-default" style="width: 100%;"
                                       value="获取验证码">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg"></span>
                    </div>
                {% endif %}
            {% endfor %}

            <div>
                <div style="float: right">
{#                    <a href="{% url "login_user" %}">用户名登录？</a>#}
                    <a href="{% url 'user:login_user' %}">用户名登录？</a>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-3" style="padding-top: 20px;">
                    <input id="btnSubmit" type="button" class="btn btn-primary" value="登  录">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script>
        // 页面框架加载完成之后自动执行函数
        $(function () {
            bindClickBtnSms();
            bindClickSubmit();
        })

        // 用户登录
        function bindClickSubmit() {
            $('#btnSubmit').click(function () {
                $(".error-msg").empty()
                $.ajax({
                    url: "{% url 'user:login_sms' %}",
                    type: "POST",
                    data: $('#smsForm').serialize(),  // 收集表单中的数据(找到每一个字段) + csrf_token
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            location.href = res.data
                        } else {
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0])
                            });
                        }
                    }
                });
            })
        }

        // 点击获取验证码
        function bindClickBtnSms() { // 编写一个函数，而不是加载完成就去执行
            $('#btnSms').click(function () {
                $(".error-msg").empty() // 清除所有的错误信息(内容变为空)
                var phone = $('#id_phone').val()

                $.ajax({
                    url: "{% url 'user:send_sms' %}",
                    type: "GET",
                    data: {
                        phone: phone,
                        req_type: "login"
                    },
                    dataType: "JSON",   // 将后台返回的数据反序列化为JSON数据
                    success: function (res) {   // ajax请求发送成功之后, 自动执行的函数, res 就是后台返回的值
                        if (res.status) {
                            SendSmsRemind();    // 倒计时
                        } else {
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0])
                            });
                        }
                    }
                })
            })
        }


        // 倒计时
        function SendSmsRemind() {
            var $smsBtn = $('#btnSms');

            $smsBtn.prop('disabled', true);
            var time = 60
            var remind = setInterval(function () {
                $smsBtn.val(time + "秒后重新发送");
                time = time - 1
                if (time < 1) {
                    clearInterval(remind);
                    $smsBtn.val("点击获取验证码").prop('disabled', false);
                }
            }, 1000)
        }


    </script>
{% endblock %}

templates/login_user.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}
    用户登录
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
{% endblock %}

{% block content %}
    <div class="account">
        <div class="title">密码登录</div>
        <form method="POST" novalidate>
            {% csrf_token %}

            {% for field in form %}
                {% if field.name == 'img_code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row">
                            <div class="col-md-7">
                                {{ field }}
                                <span class="error-msg">{{ field.errors.0 }}</span>
                            </div>
                            <div class="col-md-5">
                                <img src="{% url 'user:image_code' %}" id="imageCode" title="点击更换图片">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg">{{ field.errors.0 }}</span>
                    </div>
                {% endif %}
            {% endfor %}

            <div>
                <div style="float: right">
{#                    <a href="{% url "user.login_sms" %}">短信验证码登录？</a>#}
                    <a href="{% url 'user:login_sms' %}">短信验证码登录？</a>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-3" style="padding-top: 20px;">
                    <input type="submit" class="btn btn-primary" value="登  录">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(function () {
            $("#imageCode").click(function () {
                var oldSrc = $(this).attr("src");
                $(this).attr("src", oldSrc + "?");
            })
        })
    </script>
{% endblock %}

templates/register.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}
    用户注册
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
{% endblock %}

{% block content %}
    <div class="account">
        <div class="title">用户注册</div>
        <form id="regForm" method="POST" novalidate>
            {% csrf_token %}

            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="row">
                            <div class="col-md-7">
                                {{ field }}
                                <span class="error-msg"></span>
                            </div>
                            <div class="col-md-5">
                                <input id="btnSms" type="button" class="btn btn-default" style="width: 100%;"
                                       value="获取验证码">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="error-msg"></span>
                    </div>
                {% endif %}
            {% endfor %}
            <div class="row">
                <div class="col-xs-3" style="padding-top: 20px;">
                    <input id="btnSubmit" type="button" class="btn btn-primary" value="注  册">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script>
        // 页面框架加载完成之后自动执行函数
        $(function () {
            bindClickBtnSms();
            bindClickSubmit();
        })

        // 用户注册
        function bindClickSubmit() {
            $('#btnSubmit').click(function () {
                $(".error-msg").empty()
                $.ajax({
                    url: "{% url 'user:register' %}",
                    type: "POST",
                    data: $('#regForm').serialize(),  // 收集表单中的数据(找到每一个字段) + csrf_token
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            location.href = res.data
                        } else {
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0])
                            });
                        }
                    }
                });
            })
        }

        // 点击获取验证码
        function bindClickBtnSms() { // 编写一个函数，而不是加载完成就去执行
            $('#btnSms').click(function () {
                $(".error-msg").empty() // 清除所有的错误信息(内容变为空)
                var phone = $('#id_phone').val()

                $.ajax({
                    url: "{% url 'user:send_sms' %}",
                    type: "GET",
                    data: {
                        phone: phone,
                        req_type: "register"
                    },
                    dataType: "JSON",   // 将后台返回的数据反序列化为JSON数据
                    success: function (res) {   // ajax请求发送成功之后, 自动执行的函数, res 就是后台返回的值
                        if (res.status) {
                            SendSmsRemind();    // 倒计时
                        } else {
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0])
                            });
                        }
                    }
                })
            })
        }


        // 倒计时
        function SendSmsRemind() {
            var $smsBtn = $('#btnSms');

            $smsBtn.prop('disabled', true);
            var time = 60
            var remind = setInterval(function () {
                $smsBtn.val(time + "秒后重新发送");
                time = time - 1
                if (time < 1) {
                    clearInterval(remind);
                    $smsBtn.val("点击获取验证码").prop('disabled', false);
                }
            }, 1000)
        }


    </script>
{% endblock %}

templates/settingLine.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="../static/js/jquery-3.4.1.js"></script>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        #container {
            width: 800px;
            height: 500px;
            margin: 0 auto;
            position: relative;
            background-color: black;
        }

        .line {
            position: absolute;
            cursor: default;
        }

        .lineS {
            font-size: 1px;
            opacity: 0;
            border-radius: 2.5px;
            position: absolute;
            transition:1s;
            position: absolute;
            cursor: default;
        }
    </style>
</head>

<body>
    <div id="container">

    </div>
</body>
<script>
    //注：！！p标签必须绝对定位，否则设置显示位置将不起作用，
    //为什么需要删除元素，如果不删除，页面元素过多，浪费资源


    //适配浏览器宽高
$('#container').width($(window).width())
$('#container').height($(window).height())

    var container = $('#container'); //获取容器
    var divLeft = $(container).offset().left//获取容器距离左侧的距离
    var divTop = $(container).offset().top//获取容器距离上方的距离
    var timer;//定时器一，更改p的样式
    var timer2;//定时器二，回收生成的p
    //符号数组
    var shape = ['♥','♫','❤','✿','❉','♣','☀','☺','◐','☑','√','×','☒','☹','☾','☀','▂','▃','▅','♫','§','〼','¤','۞','℗','℗','®','®','卐','卍','☋','♊']
    //将鼠标移动时间绑定到容器上
    $(container).mousemove(function (event) {
        event = event || window.event//赋值event
        var scrollX = document.documentElement.scrollLeft || document.body.scrollLeft;//获取当前导航栏距离左侧的距离
        var scrollY = document.documentElement.scrollTop || document.body.scrollTop;//获取导航栏距离上方的距离
        
        //获取到当前鼠标在容器中的位置
        var x = event.clientX + scrollX - divLeft;//鼠标x可视位置-导航栏x距离-容器距离左侧的位置
        var y = event.clientY + scrollY - divTop;//同上，x变y
        
        //生成红蓝绿随机颜色
        var red = parseInt(Math.random() * 257).toString(16);
        var blue = parseInt(Math.random() * 257).toString(16);
        var green = parseInt(Math.random() * 257).toString(16);
        var color = '#' + red + blue + green;
        //生成随机字体大小
        var size = (Math.random()*(30-1+1)+1)+'px'
        //随机符号
        var shapeInedx = parseInt(Math.random()*(shape.length-1-0+1)+0)
        //p标签，绑定文字
        var p = '<p class="line">'+shape[shapeInedx]+'</p>'
        //设置p标签随机出的颜色以及字体大小样式，设置p标签显示位置，并且插入到容器中
        $(container).append($(p).css({
            "color":color,
            "font-size":size
        }).offset({
            top: y,
            left: x
        }))

        //等待10毫秒后执行，防止还未生成就变换看不见的样式
        setTimeout(() => {
            timer = setInterval(vanish(), 1000)//每1s执行一次vanish方法，
        }, 10);
        //回收p机制，每1s执行一次防止还未显示就被回收
        setTimeout(() => {
            timer2 = setInterval(removeDom(),3000)//每3s执行一次删除方法
        }, 1000);
      
    })

    //变换样式方法
    function vanish() {
        var pLine = $('.line')[0];//每次获取到第一个样式为初始的p元素
        $(pLine).removeClass('line')//删除样式
        $(pLine).addClass('lineS')//填入样式

        if (pLine == undefined) {//判断页面内还有没有初始样式的标签，如果没有，清除timer
            clearInterval(timer)
        }
    }

    //删除元素方法
    function removeDom() {
        var pLine = $('.lineS')[0];//获取第一个样式为改变后的p元素
        $(pLine).remove()//删除
    }
</script>

</html>