BugOA/BugOA/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

apps/project/urls.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/8/16 下午5:25
# @Author  : Zheng Xingtao
# @File    : urls.py


from .views import *
from django.conf.urls import url

urlpatterns = [
    url(r'^list/$', ProjectInfo.as_view(), name="list"),
    url(r'add_star/(?P<project_type>\w+)(?P<project_id>\d+)/$', ProjectStar.as_view({"get": "add_star"}), name="add_star"),
    url(r'delete_star/(?P<project_type>\w+)(?P<project_id>\d+)/$', ProjectStar.as_view({"get": "delete_star"}), name="delete_star"),
]


"""
如果不创建单独的app，url设计
url(r'manage/(?P(<project_id>\d+)/', include([
    url(r'dashboard', dashboard, name="manage_dashboard"),
    url(r'issues', issues, name="manage_issues"),
    url(r'statistics', statistics, name="manage_statistics"),
    url(r'file', file, name="manage_file"),
    url(r'wiki', wiki, name="manage_wiki"),
    url(r'setting', setting, name="manage_setting"),
], None)
"""

apps/users/urls.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/8/6 上午1:06
# @Author  : Zheng Xingtao
# @File    : urls.py.py

from .views import *
from django.conf.urls import url

urlpatterns = [
    url(r'^logout/$', logout, name="logout"),
    url(r'^sms/$', send_sms, name="send_sms"),
    url(r'^image/code/$', image_code, name="image_code"),
    url(r'^register/$', Register.as_view(), name="register"),
    url(r'^login/sms/$', LoginSms.as_view(), name="login_sms"),
    url(r'^login/user/$', LoginUser.as_view(), name="login_user"),
]

cms/urls.py
from django.contrib import admin
from django.views.static import serve
from setting.develop import MEDIA_ROOT
from django.conf.urls import url, include

from django.views.generic.base import TemplateView, RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),  # index页面
    url(r'^favicon\.ico$', RedirectView.as_view(url=r'static/img/favicon.ico')),  # favicon图标
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    url(r'^user/', include(('users.urls', "user"), namespace="user")),  # 使用namespace， 防止多个app时前缀重名
    url(r'^project/', include(('project.urls', "project"), namespace="project")),
    url(r'^manage/(?P<project_id>\d+)/', include(('manages.urls', "manages"), namespace="manages")),
]

templates/layout/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>
        {% block title %}

        {% endblock %}
    </title>

    <link rel="stylesheet" href="{% static 'plugin/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'plugin/font-awesome/css/font-awesome.min.css' %}">
    <style>
        .navbar-default {
            border-right: 0;
        }
    </style>
    {% block css %}

    {% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url "index" %}">Tracer 平台</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="#">产品功能</a></li>
                <li><a href="#">企业方案</a></li>
                <li><a href="#">帮助文档</a></li>
                <li><a href="#">价格</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if request.tracer.user %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">{{ request.tracer.user.username }}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'project:list' %}">管理中心</a></li>
                            <li><a href="#">个人信息</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'user:logout' %}">退出登录</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'user:login_user' %}">登录</a></li>
                    <li><a href="{% url 'user:register' %}">注册</a></li>
                {% endif %}

            </ul>

        </div>
    </div>
</nav>

{% block content %}

{% endblock %}

<script src="{% static 'js/jquery-3.4.1.js' %}"></script>
<script src="{% static 'plugin/bootstrap/js/bootstrap.min.js' %}"></script>

{% block js %}

{% endblock %}

</body>
</html>

templates/layout/base_after.html
{% load static %}
{% load project %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>
        {% block title %}

        {% endblock %}
    </title>

    <link rel="stylesheet" href="{% static 'plugin/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'plugin/font-awesome/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/base_after.css' %}">
    <link rel="stylesheet" href="{% static 'css/account.css' %}">

    {% block css %}

    {% endblock %}
</head>
<body>
<nav class="navbar navbar-av">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'project:list' %}">Tracer 平台</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% all_project_list request %}

                {% if request.tracer.project %}
                    {% manage_menu_list request %}
                {% endif %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">工作台</a></li>
                <li><a href="#">日历</a></li>
                <li><a href="#"><i class="fa fa-bell" aria-hidden="true"></i> </a></li>
                <li><a href="#"><i class="fa fa-bookmark" aria-hidden="true"></i></a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{ request.tracer.user.username }}<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url "index" %}">官网</a></li>
                        <li role="separator" class="divider"></li>
                        {#                        <li><a href="{% url "user:logout" %}">退出登录</a></li>#}
                        <li><a href="/user/logout/">退出登录</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{% block content %}

{% endblock %}

<script src="{% static 'js/jquery-3.4.1.js' %}"></script>
<script src="{% static 'plugin/bootstrap/js/bootstrap.js' %}"></script>

{% block js %}

{% endblock %}

</body>
</html>