BugOA/BugOA/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

apps/project/urls.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/8/16 下午5:25
# @Author  : Zheng Xingtao
# @File    : urls.py


from .views import *
from django.conf.urls import url

urlpatterns = [
    url(r'^list/$', ProjectInfo.as_view(), name="list"),
    url(r'add_star/(?P<project_type>\w+)(?P<project_id>\d+)/$', ProjectStar.as_view({"get": "add_star"}), name="add_star"),
    url(r'delete_star/(?P<project_type>\w+)(?P<project_id>\d+)/$', ProjectStar.as_view({"get": "delete_star"}), name="delete_star"),
]


"""
如果不创建单独的app，url设计
url(r'manage/(?P(<project_id>\d+)/', include([
    url(r'dashboard', dashboard, name="manage_dashboard"),
    url(r'issues', issues, name="manage_issues"),
    url(r'statistics', statistics, name="manage_statistics"),
    url(r'file', file, name="manage_file"),
    url(r'wiki', wiki, name="manage_wiki"),
    url(r'setting', setting, name="manage_setting"),
], None)
"""

cms/urls.py
from django.contrib import admin
from django.views.static import serve
from setting.develop import MEDIA_ROOT
from django.conf.urls import url, include

from django.views.generic.base import TemplateView, RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),  # index页面
    url(r'^favicon\.ico$', RedirectView.as_view(url=r'static/img/favicon.ico')),  # favicon图标
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    url(r'^user/', include(('users.urls', "user"), namespace="user")),  # 使用namespace， 防止多个app时前缀重名
    url(r'^project/', include(('project.urls', "project"), namespace="project")),
    url(r'^manage/(?P<project_id>\d+)/', include(('manages.urls', "manages"), namespace="manages")),
]

apps/project/models.py
from django.db import models
from users.models import UserInfo
from setting.develop import COLOR_CHOICES


# Create your models here.
class Project(models.Model):
    """项目"""
    name = models.CharField(verbose_name="项目名称", max_length=32)
    color = models.SmallIntegerField(verbose_name="颜色", choices=COLOR_CHOICES, default=1)
    desc = models.CharField(verbose_name="项目描述", max_length=25, null=True, blank=True)
    user_space = models.BigIntegerField(verbose_name="项目已使用空间", default=0)  # 使用大的空间存储
    star = models.BooleanField(verbose_name="星标", default=0)

    # 为每一个项目在COS中创建一个桶
    bucket = models.CharField(verbose_name="腾讯对象存储桶", max_length=128)
    region = models.CharField(verbose_name="腾讯对象存储区域", max_length=32)

    join_count = models.SmallIntegerField(verbose_name="参与人数", default=1)
    creator = models.ForeignKey(UserInfo, verbose_name="创建者", on_delete=models.CASCADE)
    create_time = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    # 如果多对多的时候
    # 好处不大----查询的时候可以直接查询， 增加、删除、修改 都无法完成
    # 第三张关联表里面只有两个表的id==> 可以使用ManyToManyField
    # 第三张表中不止两个id的时候，可以使用through指定关联哪张表，同时使用through_fields指定管理的是哪些字段（这时候不会主动创建第三张表）
    # 使用through_fields, 对字段的顺序有要求，project-user， 另一张表里也要遵循这个顺序
    # project_user = models.ManyToManyField(to="UserInfo", through="ProjectUser", through_fields=("project", "user))


class ProjectUser(models.Model):
    """项目参与者"""
    user = models.ForeignKey(UserInfo, verbose_name="项目参与者", on_delete=models.CASCADE)
    project = models.ForeignKey(Project, verbose_name="项目名称", on_delete=models.CASCADE)

    star = models.BooleanField(verbose_name="星标", default=False)

    create_time = models.DateTimeField(verbose_name="加入时间", auto_now_add=True)

apps/project/views.py
from time import time
from .models import Project, ProjectUser
from django.views.generic.base import View
from rest_framework.viewsets import ViewSet
from utils.tencent.cos import create_bucket
from .project_forms import ProjectModelForm
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from setting.variable import TENCENT_COS_REGION, TENCENT_COS_API_KEY_ID


# Create your views here.
class ProjectInfo(View):
    def get(self, request):
        form = ProjectModelForm(request)

        # 获取我创建，我参与的项目
        project_dict = {"star": [], "my": [], "join": []}
        my_project_list = Project.objects.filter(creator=request.tracer.user)
        my_join_list = ProjectUser.objects.filter(user=request.tracer.user)

        for row in my_project_list:
            if row.star:
                project_dict["star"].append({"value": row, "type": "my"})
            else:
                project_dict["my"].append({"value": row, "type": "join"})

        for item in my_join_list:
            if item.star:
                project_dict["star"].append(item.project)
            else:
                project_dict["my"].append(item.project)

        return render(request, "project/project_list.html", {"form": form, "project_dict": project_dict})

    def post(self, request):
        form = ProjectModelForm(request, data=request.POST)
        if form.is_valid():
            # 1. 为每个项目创建一个桶 --> 并为桶创建跨域规则

            bucket = "{}-{}".format(request.tracer.user.phone, str(int(time()))) + TENCENT_COS_API_KEY_ID

            # 加上项目名称
            # name = form.cleaned_data["name"]    # name必须为英文
            # bucket = "{}-{}-{}".format(name, request.tracer.user.phone, str(int(time()))) + TENCENT_COS_API_KEY_ID
            create_bucket(TENCENT_COS_REGION, bucket)

            # 2. 把桶和区域写入到数据库
            form.instance.bucket = bucket
            form.instance.region = TENCENT_COS_REGION

            # 验证通过：项目名、颜色、描述 + 谁创建的项目(creator)
            form.instance.creator = request.tracer.user  # 当前登录的用户
            form.save()  # 创建项目

            return JsonResponse({"status": True})
        return JsonResponse({"status": False, "error": form.errors})


class ProjectStar(ViewSet):
    """这里直接使用类视图的方法，获取当前用户的星标操作"""

    def add_star(self, request, project_type, project_id):
        """
        添加星标的动作
        :param request: request请求对象
        :param project_type: 前端发送的Project的类型：my、join、
        :param project_id: 用户点击的Project_id
        :return: 项目列表的页面
        """
        if project_type == "my":
            Project.objects.filter(id=project_id, creator=request.tracer.user).update(star=True)
            return redirect("/project/list/")

        elif project_type == "join":
            ProjectUser.objects.filter(project_id=project_id, user=request.tracer.user).update(star=True)
            return redirect("/project/list/")

        return HttpResponse("请求失败...！")

    def delete_star(self, request, project_type, project_id):
        """在这里我们需要区分：我创建、我参与"""
        if project_type == "my":
            Project.objects.filter(id=project_id, creator=request.tracer.user).update(star=False)
            return redirect("/project/list/")

        elif project_type == "join":
            ProjectUser.objects.filter(project_id=project_id, user=request.tracer.user).update(star=False)
            return redirect("/project/list/")

        return HttpResponse("请求失败...！")

templates/project/all_project_list.html
<li class="dropdown active">
    {% if request.tracer.project %}
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.tracer.project.name }}<span class="caret"></span></a>
    {% else %}
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">项目<span class="caret"></span></a>
    {% endif %}

    <ul class="dropdown-menu">
        {% if my %}
            <li><i class="fa fa-list" aria-hidden="true"></i> 我创建的项目</li>
            {% for item in my %}
                <li><a href="{% url 'manages:dashboard:home' project_id=item.id %}">{{ item.name }}</a></li>
            {% endfor %}
        {% endif %}
        {% if join %}
            <li role="separator" class="divider"></li>
            <li><i class="fa fa-handshake-o" aria-hidden="true"></i> 我参与的项目</li>
            {% for item in join %}
                <li><a href="{% url 'manages:dashboard:home' project_id=item.value.id %}">{{ item.project.name }}</a></li>
            {% endfor %}
        {% endif %}
        <li role="separator" class="divider"></li>
        <li><a href="{% url "project:list" %}">所有项目</a></li>
    </ul>
</li>

templates/project/manage_menu_list.html
{% for item in data_list %}
    <li {% if item.class %}
            class="{{ item.class }}"
        {% endif %}>

        <a href="{{ item.url }}">{{ item.title }}</a>
    </li>
{% endfor %}

templates/project/project_list.html
{% extends "layout/base_after.html" %}


{% block title %}
    项目列表
{% endblock %}

{% block css %}
    <style>
        .project {
            margin-top: 10px;
        }

        .panel-body {
            padding: 0;
            display: flex;
            flex-direction: row;
            justify-content: left;
            align-items: flex-start;
            flex-wrap: wrap;
        }

        .panel-body > .item {
            border-radius: 6px;
            width: 228px;
            border: 1px solid #dddddd;
            margin: 20px 10px;

        }

        .panel-body > .item:hover {
            border: 1px solid #f0ad4e;
        }

        .panel-body > .item > .title {
            height: 104px;
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            border-top-left-radius: 6px;
            border-top-right-radius: 6px;
            font-size: 15px;
            text-decoration: none;
        }

        .panel-body > .item > .info {
            padding: 10px 10px;

            display: flex;
            justify-content: space-between;

            border-bottom-left-radius: 6px;
            border-bottom-right-radius: 6px;
            color: #8c8c8c;

        }

        .panel-body > .item > .info a {
            text-decoration: none;
        }

        .panel-body > .item > .info .fa-star {
            font-size: 18px;
        }

        .color-radio label {
            margin-left: 0;
            padding-left: 0;
        }

        .color-radio input[type="radio"] {
            display: none;
        }

        .color-radio input[type="radio"] + .cycle {
            display: inline-block;
            height: 25px;
            width: 25px;
            border-radius: 50%;
            border: 2px solid #dddddd;
        }

        .color-radio input[type="radio"]:checked + .cycle {
            border: 2px solid black;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container-fluid project">
        <div style="margin: 10px 0">
            <a class="btn btn-primary" data-toggle="modal" data-target="#addModel">
                <i class="fa fa-plus-circle" aria-hidden="true"></i>&nbsp;&nbsp;新建项目
            </a>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><i class="fa fa-star" aria-hidden="true"></i> 星标项目</div>
            <div class="panel-body">
                {% for item in project_dict.star %}
                    <div class="item">
                        <a href="{% url 'manages:dashboard:home' project_id=item.value.id %}" class="title"
                           style="background-color: {{ item.value.get_color_display }};">{{ item.value.name }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project:delete_star' project_type=item.type project_id=item.value.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #f0ad4e;"></i>
                                </a>
                                <span>{{ item.value.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.value.join_count }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><i class="fa fa-list" aria-hidden="true"></i> 我创建的</div>
            <div class="panel-body">
                {% for item in project_dict.my %}
                    <div class="item">
                        <a href="{% url 'manages:dashboard:home' project_id=item.value.id %}" class="title"
                           style="background-color: {{ item.value.get_color_display }};">{{ item.value.name }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project:add_star' project_type='my' project_id=item.value.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5"></i>
                                </a>
                                <span>{{ item.value.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.valuejoin_count }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><i class="fa fa-handshake-o" aria-hidden="true"></i> 我参与的</div>
            <div class="panel-body">
                {% for item in project_dict.join %}
                    <div class="item">
                        <a href="{% url 'manages:dashboard:home' project_id=item.value.value.id %}" class="title"
                           style="background-color: {{ item.value.value.get_color_display }};">{{ item.value.name }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'project:add_star' project_type='join' project_id=item.value.value.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5"></i>
                                </a>
                                <span>{{ item.value.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.value.join_count }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="modal fade" id="addModel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">新建项目</h4>
                </div>
                <div class="modal-body">
                    <form id="addForm">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <lobel for=""{{ field.id_for_label }}>{{ field.label }}</lobel>
                                {{ field }}
                                <span class="error_msg"></span>
                            </div>
                        {% endfor %}
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button id="btnSubmit" type="button" class="btn btn-primary">确定</button>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

{% block js %}
    <script>
        $(function () {
            bindSubmit();
        });

        function bindSubmit() {
            $('#btnSubmit').click(function () {
                $.ajax({
                    url: "{% url "project:list" %}",
                    type: "POST",
                    data: $('#addForm').serialize(),
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            location.reload();
                        } else {
                            console.log(res)
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }

                })
            })
        }
    </script>
{% endblock %}